const useNotificationPage = () => {
  return {
    notifications: {
      오늘: [
        {
          id: 1,
          type: 'relationship_response',
          senderId: 2001,
          senderProfileImage: 'https://example.com/images/user2001.jpg',
          receiverId: 1001,
          deepLink: 'fillbom://relationship/response/1',
          isRead: false,
          content: '김보호님이 보호자 요청을 수락하였습니다.',
          createdAt: '2023-10-02T09:30:00Z',
        },
        {
          id: 2,
          type: 'relationship_request',
          senderId: 1001,
          senderProfileImage: 'https://example.com/images/user1001.jpg',
          receiverId: 2002,
          deepLink: 'fillbom://relationship/request/2',
          isRead: false,
          content: '홍길동님이 보호자 추가를 요청하였습니다.',
          createdAt: '2023-10-02T10:00:00Z',
        },
        {
          id: 3,
          type: 'schedule_reminder',
          senderId: null,
          senderProfileImage: null,
          receiverId: 1001,
          deepLink: 'fillbom://schedule/3',
          isRead: false,
          content: '오늘 오후 2시에 병원 예약이 있습니다.',
          createdAt: '2023-10-02T08:00:00Z',
        },
      ],
      '2024. 10. 15': [
        {
          id: 4,
          type: 'diary_created',
          senderId: 1001,
          senderProfileImage: 'https://example.com/images/user1001.jpg',
          receiverId: 2001,
          deepLink: 'fillbom://diary/4',
          isRead: false,
          content: '홍길동님이 새로운 일기를 작성하였습니다.',
          createdAt: '2023-10-02T11:15:00Z',
        },
        {
          id: 5,
          type: 'medication_reminder',
          senderId: null,
          senderProfileImage: null,
          receiverId: 1001,
          deepLink: 'fillbom://medication/5',
          isRead: false,
          content: '오전 9시 약 복용 시간입니다.',
          createdAt: '2023-10-02T08:55:00Z',
        },
        {
          id: 6,
          type: 'released',
          senderId: null,
          senderProfileImage: null,
          receiverId: 1001,
          deepLink: 'fillbom://update/6',
          isRead: false,
          content: '필봄 앱의 새로운 버전이 출시되었습니다. 업데이트 해주세요. ',
          createdAt: '2023-10-02T07:00:00Z',
        },
        {
          id: 7,
          type: 'etc',
          senderId: null,
          senderProfileImage: null,
          receiverId: 1001,
          deepLink: 'fillbom://event/7',
          isRead: false,
          content: '가을 맞이 이벤트에 참여해보세요!',
          createdAt: '2023-10-02T12:30:00Z',
        },
      ],
    },
  };
};

export default useNotificationPage;
